// <auto-generated />
namespace BookDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class press : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(press));
        
        string IMigrationMetadata.Id
        {
            get { return "201611152156288_press"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
