// <auto-generated />
namespace BookDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class author_isdeleted : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(author_isdeleted));
        
        string IMigrationMetadata.Id
        {
            get { return "201609292039022_author_isdeleted"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
